version: "3.5"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kairos-schema-tools-app
    depends_on:
      - clotho
    image: tetherlessworld/kairos-schema-tools-app
    ports:
      - 127.0.0.1:8080:80
    restart: unless-stopped
    volumes:
      - "${DATA:-./conf/data}:/data"
  clotho:
    image: openjdk:11
    depends_on:
      - neo4j
    ports:
      - "127.0.0.1:8008:8008"
    environment:
      DB_TYPE: "Neo4j"
      DB_URI: "bolt://neo4j:7687"
    working_dir: "/jars/"
    command: "/bin/bash -c 'java -jar /moirai-clotho.jar'"
    volumes:
      - ./moirai-clotho.jar:/moirai-clotho.jar:ro
  neo4j:  # For the NextCentury validator
    image: neo4j:3.5.0
    environment:
      NEO4J_AUTH: none
